<x-cabinet-filament::finder
    :$folder
    :$files
    :$breadcrumbs
    :$toolbarActions
    :$contextMenus
    :$selectionMode
    :$sidebarItems
    :$sidebarFilters
    :$sidebarLinks
    :$selectedSidebarItem
/>
