<x-cabinet-filament::finder
	:modal="false"
    :$folder
    :$files
    :$breadcrumbs
    :$toolbarActions
    :$contextMenus
    :$selectionMode
    :$sidebarItems
    :$acceptedTypeChecker
    :$selectedSidebarItem
/>
